const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const app = path.resolve(__dirname, '../../../aegis-app')
const { Contract, providers, utils } = require(path.join(app, 'node_modules/ethers'))
const dir = path.join(app, 'src/pages/BankYield')
const deployment = require(path.join(dir, 'deployment.sepolia.json'))
const record = require('../../deployments/sepolia/AegisVault.amina.json')
async function main() {
  const provider = new providers.JsonRpcProvider(deployment.rpcUrl)
  assert.equal((await provider.getNetwork()).chainId, deployment.chainId)
  for (const name of ['VaultMinting', 'VaultStaking', 'VaultConfig']) {
    const abi = require(path.join(dir, `${name}.abi.json`))
    assert.deepEqual(abi, require(`../../artifacts/contracts/AegisVault/${name}.sol/${name}.json`).abi)
  }
  for (const [key, address] of Object.entries(deployment.contracts)) assert.equal(address, record.contracts[key].address)
  const minting = new Contract(deployment.contracts.minting, require(path.join(dir, 'VaultMinting.abi.json')), provider)
  const staking = new Contract(deployment.contracts.staking, require(path.join(dir, 'VaultStaking.abi.json')), provider)
  const token = new Contract(deployment.contracts.token, ['function symbol() view returns(string)', 'function name() view returns(string)'], provider)
  assert.equal(await token.symbol(), 'adUSDG'); assert.equal(await token.name(), 'Amina Deposit USDG')
  assert.equal(await staking.symbol(), 'ausdg'); assert.equal(await staking.name(), 'Amina USDG')
  assert.equal(await staking.asset(), deployment.contracts.token)
  assert.equal(await minting.token(), deployment.contracts.token)
  assert((await staking.convertToAssets(utils.parseEther('1'))).gt(utils.parseEther('1')))
  const response = await fetch('http://127.0.0.1:8788/quote', { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: 'http://localhost:3000' }, body: JSON.stringify({ orderType: 0, wallet: record.settings.admin, amount: '0.1' }) })
  assert.equal(response.status, 200); const q = await response.json()
  assert.equal(q.domain.verifyingContract, deployment.contracts.minting)
  assert.equal(q.order.collateralAmount, '100000')
  const types = { Order: ['orderType:uint8','userWallet:address','collateralAsset:address','collateralAmount:uint256','tokenAmount:uint256','slippageAdjustedAmount:uint256','expiry:uint256','nonce:uint256','additionalData:bytes'].map(s => { const [name, type] = s.split(':'); return { name, type } }) }
  assert.equal(utils.verifyTypedData(q.domain, types, q.order, q.signature), record.settings.trustedSigner)
  const rejected = await fetch('http://127.0.0.1:8788/quote', { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: 'https://untrusted.example' }, body: '{}' })
  assert.equal(rejected.status, 403)
  const invalid = await fetch('http://127.0.0.1:8788/quote', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ orderType: 2, wallet: record.settings.admin, amount: '1' }) })
  assert.equal(invalid.status, 400)
  const result = { checkedAt: new Date().toISOString(), block: await provider.getBlockNumber(), app, assertions: ['frontend ABIs match compiled contracts', 'frontend addresses match deployed record', 'ethers v5 reads live token names and staking rate', 'local HTTP quote signature verified against configured signer', 'untrusted origin and income-order signing rejected'] }
  fs.writeFileSync(path.resolve(__dirname, '../../deployments/sepolia/AegisVault.amina.ui-validation.json'), JSON.stringify(result, null, 2) + '\n')
  console.log(JSON.stringify(result, null, 2))
}
main().catch(e => { console.error(e.message); process.exitCode = 1 })
